export { default as HeroSection } from "./HeroSection"
export { default as GettingStarted } from "./GettingStarted"
export { default as SecurityTrust } from "./SecurityTrust"
export { default as StartNow } from "./StartNow"
export { default as Footer } from "./Footer"
