export { default as Discover } from "./Discover"
export { default as Product } from "./Product"
export { default as About } from "./About"
export { default as GetStarted } from "./GetStarted"
export { default as DashBoard } from "./DashBoard"
